# Generated by Django 4.0 on 2022-05-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='duracao',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
