# Generated by Django 4.0 on 2022-08-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_musica_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='file_arquivo',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
