# Generated by Django 4.0 on 2021-12-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome: ')),
                ('cor', models.CharField(max_length=150, verbose_name='Cor')),
            ],
        ),
    ]
